language: node_js
node_js:
  - '0.8'
  - '0.10'
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - sleep 1 # give server time to start

script:
  - node_modules/karma/bin/karma start karma.conf.js --no-auto-watch --single-run --browsers=Firefox
